type User {
    netlifyID: ID!
    stripeID: ID!
    priceID: String
    planID: String
    planName: String
}

type Query {
    getUserByNetlifyID(netlifyID: ID!): User!
    getUserByStripeID(stripeID: ID!): User!
}